version: '3'

services:

  reverse-proxy:
      image: traefik:v2.3
      command: 
          #- "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.websecure.address=:443"
          - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
          #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
          - "--certificatesresolvers.myresolver.acme.email=cloud@spilikin.dev"
          - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      ports:
          # The HTTP port
          - "443:443"
          # The Web UI (enabled by --api.insecure=true)
          - "8080:8080"
      volumes:
          # So that Traefik can listen to the Docker events
          - /var/run/docker.sock:/var/run/docker.sock
          - "./letsencrypt:/letsencrypt"

  healthid-backend:
    build:
        context: https://github.com/spilikin/poc-healthid-backend.git
    labels:
        - "traefik.enable=true"
        - "traefik.http.services.healthid-backend.loadbalancer.server.port=8000"
        - "traefik.http.routers.healthid-backend.rule=Host(`acme.spilikin.dev`)"
        - "traefik.http.routers.healthid-backend.entrypoints=websecure"
        - "traefik.http.routers.healthid-backend.tls.certresolver=myresolver"
    volumes:
      # Main config
      - ./db:/app/.db
